<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit6d27190d9fdc773ddc2eaddbe6e637c3
{
    public static $prefixLengthsPsr4 = array (
        'O' => 
        array (
            'OntraportAPI\\' => 13,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'OntraportAPI\\' => 
        array (
            0 => __DIR__ . '/..' . '/ontraport/sdk-php/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit6d27190d9fdc773ddc2eaddbe6e637c3::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit6d27190d9fdc773ddc2eaddbe6e637c3::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
