<?php

// autoload.php @generated by Composer
echo 33333333333;
require_once __DIR__ . '/composer/autoload_real.php';
echo 222222222222;
return ComposerAutoloaderInit6d27190d9fdc773ddc2eaddbe6e637c3::getLoader();

echo 888888888 ;